---
title: "Randomizer"
output: rmarkdown::html_vignette
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  eval = TRUE
)
```

## Simple randomization

You can also randomize data using im::randomize.
This function iteratively re-randomizes until achieving a specified level of
baseline equivalence or reaching a maximum number of attempts.

```{r, echo = TRUE}
my_data <- tibble::tibble(
  x1 = rnorm(10000),
  x2 = rnorm(10000)
)

# Randomize
randomized <- im::randomizer$new(
  data = my_data,
  seed = 12345,
  max_attempts = 1000,
  variables = c("x1", "x2"),
  standard = "Not Concerned"
)

# Get Randomized Data
randomized$data
# Get Balance Summary
randomized$balance_summary
# Generate Balance Plot
randomized$balance_plot
```

## Stratified randomization

```{r, echo = TRUE}
my_data <- tibble::tibble(
  x1 = rnorm(10000),
  x2 = rnorm(10000),
  x3 = rep(c("A", "B"), 5000),
  x4 = rep(c("C", "D"), 5000)
)

# Create a Randomizer Object
randomized <- im::randomizer$new(
  data = my_data,
  seed = 12345,
  max_attempts = 1000,
  variables = c("x1", "x2"),
  standard = "Not Concerned",
  group_by = "x3"
)

# Generate Balance Plot
randomized$balance_plot
```

---

#### im

Licensed under the Apache License, Version 2.0.\
